# -*- coding: utf-8 -*-
"""arithmania2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FSxbvzUGRKNzU7BlWFbEseMXkehLdAJ

public and private key generator

public key and private key generator
"""

import rsa

public_key, private_key = rsa.newkeys(1024)
with open("key/public.pem","wb") as f:
    f.write(public_key.save_pkcs1("PEM"))
with open("key/private.pem","wb") as f:
    f.write(private_key.save_pkcs1("PEM"))

"""encrypter"""

import os
import rsa
import string
import random
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

def generate_key_and_iv(password, salt):
    # Derive a key and IV from the password and salt using PBKDF2
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32 + 16,  # 32 bytes for key and 16 bytes for IV
        salt=salt,
        iterations=100000,
        backend=default_backend()
    )
    key_and_iv = kdf.derive(password)

    # Split the key and IV
    key = key_and_iv[:32]
    iv = key_and_iv[32:]

    return key, iv

def encrypt_file(input_file, output_file):
    # Generate a random password for encryption
    password = makeKey().encode()

    # Write the password to a text file
    with open('key/password.txt', 'w') as password_file:
        password_file.write(password.decode())

    # Generate a random salt
    salt = os.urandom(16)

    # Generate key and IV using the password and salt
    key, iv = generate_key_and_iv(password, salt)

    # Initialize AES cipher with CBC mode
    cipher = Cipher(algorithms.AES(key), modes.CBC(iv), backend=default_backend())
    encryptor = cipher.encryptor()

    # Read the contents of the input file
    with open(input_file, 'rb') as f:
        plaintext = f.read()

    # Apply PKCS7 padding to the plaintext
    padder = padding.PKCS7(128).padder()
    padded_plaintext = padder.update(plaintext) + padder.finalize()

    # Encrypt the padded plaintext
    ciphertext = encryptor.update(padded_plaintext) + encryptor.finalize()

    # Write the salt, IV, and ciphertext to the output file
    with open(output_file, 'wb') as f:
        f.write(salt)
        f.write(iv)
        f.write(ciphertext)

    # Write the encryption key to a text file
    with open('key/key.txt', 'wb') as key_file:
        key_file.write(key)

    print("Encryption completed successfully!")

def makeKey():
    chars = string.ascii_letters + string.digits + string.punctuation + " "
    shuffled_chars = list(chars)
    while any(shuffled_chars[i] == chars[i] for i in range(len(chars))):
        random.shuffle(shuffled_chars)
    return ''.join(shuffled_chars)

def pki_encryptor():
    with open("key/public.pem", "rb") as f:
        public_key = rsa.PublicKey.load_pkcs1(f.read())
    with open("key/key.txt", "rb") as f:
        key = f.read()
        print(key)

    encrypted_key = rsa.encrypt(key, public_key)
    print(encrypted_key)
    with open("key/pki_encrypted.txt", "wb") as f:
        f.write(encrypted_key)

    #clear_message = rsa.decrypt(encrypted_key, public_key)
    #print(clear_message)

# Provide the paths of the input and output files
input_file_path = "input.txt"
output_file_path = "content/encrypted_output.txt"

# Call the function to encrypt the contents of the input file
encrypt_file(input_file_path, output_file_path)
pki_encryptor()

"""convert the encrypted text into binary"""

def encrypted_text_to_binary(input_file, output_file):
    try:
        # Open the input file in binary read mode
        with open(input_file, 'rb') as f:
            # Read the contents of the input file as binary data
            binary_data = f.read()

        # Open the output file in binary write mode with a .bin extension
        with open(output_file, 'wb') as f:
            # Write the binary data to the output file
            f.write(binary_data)

        print("Encrypted text converted to binary and saved to binary file successfully!")

    except FileNotFoundError:
        print("File not found. Please provide valid file paths.")
    except Exception as e:
        print("An error occurred:", str(e))


# Provide the paths of the input and output files
input_file_path = "content/encrypted_output.txt"
output_file_path = "content/binary_output.bin"

# Call the function to convert encrypted text data to binary and save it to a binary file
encrypted_text_to_binary(input_file_path, output_file_path)

"""hiding the data in the image"""

import cv2

def hide_encrypted_data_in_image(image_path, encrypted_binary_file_path, output_image_path, size_file_path):
    # Load the image
    image = cv2.imread(image_path)

    # Read the encrypted binary data from the binary file
    with open(encrypted_binary_file_path, 'rb') as file:
        encrypted_binary_data = file.read()

    # Get the length of the binary data (in bits)
    data_length = len(encrypted_binary_data) * 8

    # Write the size of the data to a text file
    with open(size_file_path, 'w') as size_file:
        size_file.write(str(data_length))

    # Convert the binary data to a binary string
    binary_data = ''.join(format(byte, '08b') for byte in encrypted_binary_data)

    # Get the shape of the image
    rows, cols, _ = image.shape

    # Counter for the binary string
    binary_index = 0

    # Iterate through each pixel in the image
    for i in range(rows):
        for j in range(cols):
            # Extract RGB values of the pixel
            r, g, b = image[i, j]

            # Convert RGB values to binary strings
            r_binary = format(r, '08b')
            g_binary = format(g, '08b')
            b_binary = format(b, '08b')

            # Manipulate the least significant bit of each color channel
            if binary_index < data_length:
                r_binary = r_binary[:-1] + binary_data[binary_index]
                binary_index += 1
            if binary_index < data_length:
                g_binary = g_binary[:-1] + binary_data[binary_index]
                binary_index += 1
            if binary_index < data_length:
                b_binary = b_binary[:-1] + binary_data[binary_index]
                binary_index += 1

            # Convert binary strings back to integers
            r_new = int(r_binary, 2)
            g_new = int(g_binary, 2)
            b_new = int(b_binary, 2)

            # Update the pixel with the new RGB values
            image[i, j] = [r_new, g_new, b_new]

    # Save the image with hidden data
    cv2.imwrite(output_image_path, image)

# Example usage
image_path = 'input.png'  # Path to your PNG image file
encrypted_binary_file_path = 'content/binary_output.bin'  # Path to your encrypted binary data file
output_image_path = 'output.png'  # Path for the output image with hidden encrypted data
size_file_path = 'content/size.txt'  # Path for the file to store the size of the hidden data

# Hide encrypted data in the image
hide_encrypted_data_in_image(image_path, encrypted_binary_file_path, output_image_path, size_file_path)



################################################################################################################################################################


"""extracting data back from the image"""

import cv2

def extract_hidden_data_from_image(image_path, size_file_path, extracted_binary_file_path):
    # Load the image
    image = cv2.imread(image_path)

    # Read the size of the hidden data from the size.txt file
    with open(size_file_path, 'r') as size_file:
        data_length = int(size_file.read())

    # Initialize variables
    binary_data = ''
    binary_index = 0

    # Get the shape of the image
    rows, cols, _ = image.shape

    # Iterate through each pixel in the image
    for i in range(rows):
        for j in range(cols):
            # Extract RGB values of the pixel
            r, g, b = image[i, j]

            # Convert RGB values to binary strings
            r_binary = format(r, '08b')
            g_binary = format(g, '08b')
            b_binary = format(b, '08b')

            # Extract the least significant bit of each color channel
            binary_data += r_binary[-1]
            binary_index += 1
            if binary_index < data_length:
                binary_data += g_binary[-1]
                binary_index += 1
            if binary_index < data_length:
                binary_data += b_binary[-1]
                binary_index += 1

            # Break loop if enough data has been extracted
            if binary_index >= data_length:
                break
        if binary_index >= data_length:
            break

    # Convert the binary data to bytes
    extracted_data = bytes(int(binary_data[i:i+8], 2) for i in range(0, len(binary_data), 8))

    # Write the extracted data to a binary file
    with open(extracted_binary_file_path, 'wb') as extracted_file:
        extracted_file.write(extracted_data)

# Example usage
image_path = 'output.png'  # Path to the image with hidden data
size_file_path = 'content/size.txt'  # Path to the file storing the size of the hidden data
extracted_binary_file_path = 'content/extracted_data.bin'  # Path for the extracted binary data file

# Extract hidden data from the image
extract_hidden_data_from_image(image_path, size_file_path, extracted_binary_file_path)

"""binary to text"""

def binary_to_encrypted_text(input_file, output_file):
    try:
        # Open the input file in binary read mode
        with open(input_file, 'rb') as f:
            # Read the binary data from the input file
            binary_data = f.read()

        # Open the output file in write mode
        with open(output_file, 'wb') as f:
            # Write the binary data to the output file
            f.write(binary_data)

        print("Binary data converted to encrypted text and saved to file successfully!")

    except FileNotFoundError:
        print("File not found. Please provide valid file paths.")
    except Exception as e:
        print("An error occurred:", str(e))


# Provide the paths of the input and output files
input_file_path = "content/extracted_data.bin"
output_file_path = "content/encrypted_text_output.txt"

# Call the function to convert binary data to encrypted text and save it to a text file
binary_to_encrypted_text(input_file_path, output_file_path)

"""decrypter"""

import os
import rsa
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

def pub_key_decryptor():
    with open("key/private.pem", "rb") as f:
      private_key = rsa.PrivateKey.load_pkcs1(f.read())

    encrypted_message = open("key/pki_encrypted.txt","rb").read()
    global clear_message
    clear_message = rsa.decrypt(encrypted_message, private_key)
    with open("key/pki_decrypted.txt", "wb") as f:
      f.write(clear_message)


def decrypt_file(input_file, output_file):
    # Read the salt, IV, and ciphertext from the encrypted file
    with open(input_file, 'rb') as f:
        # Read the salt (16 bytes)
        salt = f.read(16)
        # Read the IV (16 bytes)
        iv = f.read(16)
        # Read the ciphertext
        ciphertext = f.read()

    # Read the encryption key from the key.txt file
    '''
    with open("key/pki_decrypted.txt", 'rb') as key_file    w 4y1:
        key = key_file.read()
        print(key)
    '''

    with open("key/key.txt", 'rb') as file1:
        key = file1.read()
        print(key)


    # Derive the key using the password and salt
    cipher = Cipher(algorithms.AES(key), modes.CBC(iv), backend=default_backend())
    decryptor = cipher.decryptor()

    # Decrypt the ciphertext
    decrypted_data = decryptor.update(ciphertext) + decryptor.finalize()

    # Remove PKCS7 padding
    unpadder = padding.PKCS7(128).unpadder()
    unpadded_data = unpadder.update(decrypted_data) + unpadder.finalize()

    # Write the decrypted plaintext to the output file
    with open(output_file, 'w') as f:
        f.write(unpadded_data.decode('utf-8'))

    print("Decryption completed successfully!")

# Provide the paths of the encrypted file and output decrypted file
encrypted_file_path = "content/encrypted_text_output.txt"
decrypted_file_path = "output.txt"

# Call the decrypt function
pub_key_decryptor()
decrypt_file(encrypted_file_path, decrypted_file_path)